version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: sms_manager
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sms_manager

  # backend:
  #   build:
  #     context: ./src/backend
  #   container_name: rust_service
  #   depends_on:
  #     - database
  #   environment:
  #     DATABASE_URL: postgres://admin:password@postgres:5432/sms_manager
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./src/backend:/app 

volumes:
  postgres_data: